# Generated by Django 2.2.14 on 2022-01-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220121_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='image', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='image2', upload_to='images/'),
            preserve_default=False,
        ),
    ]
