# Generated by Django 2.2.14 on 2022-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220123_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default='imag', upload_to='images/'),
            preserve_default=False,
        ),
    ]
